### ISSUE TITLE
SEO (Search Engine Optimisation)

### ISSUE THREAD

**Issue by DesislavaNaydenova** [DesislavaNaydenova/2405-hackathon-team1-StarWars#12]
Functional Overview:
Meta Tags and Meta Data help search engines understand the content and context of a page, and can improve the appearance of the page in the search results.

## Meta Tags

Title tags: These tags appear in the title bar of a web browser and provide a brief description of the page's content. They are also used as the title of your page in search engine results.

Description tags: These tags provide a brief summary of your page's content and are often displayed below the title of your page in search engine results.

Keyword tags: These tags list relevant keywords or phrases that are related to your page's content. While these tags are not as important as they once were, they can still help search engines understand the content of your page.

Robots tags: These tags tell search engines whether or not to index your page or follow links on your page.

## Meta Data

Page titles: These titles are used to describe the content of each page on your website and are often used as the title of your page in search engine results.

Meta descriptions: These descriptions provide a brief summary of your page's content and are often displayed below the title of your page in search engine results.

Headings: Headings are used to organize and structure the content of your page, making it easier for both users and search engines to understand the purpose and main points of your content.

Alt tags: Alt tags are used to describe images on your website, making it easier for search engines to understand the content of your images and providing an alternative text for users who are unable to view the images.

**Comment by kera-cudmore** [comment]
Most of the meta tags are now complete, will need to update social image one once we have a responsive image
