### ISSUE TITLE
Quiz Issue - Question Counter is showing on the quiz page before you start the quiz.

### ISSUE THREAD

**Issue by kslg** [DesislavaNaydenova/2405-hackathon-team1-StarWars#68]
**Issue:**

The user can see the question counter before starting the quiz.

**Request:** 
Need to hide/disable the counter until the user clicks on 'Start'

**What have I tried:**

I've tried to hide the div on page load. I tried thr js and jquery version:

HTML div
```html
<!-- Question count -->
<div class="text-center quiz-text questionCount" id="question-Counter" role="presentation" aria-label="This is the question counter, counting up to ten">
</div> 
``` 

quiz.js
```javascript
// *** Hide Question Counter on page load ****
document.onload = function() {
    document.getElementById('question-Counter').style.display = 'none';
};

// $(document).ready(function() {
//     $("#question-Counter").hide();
// });
``` 

![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/52354124/0f1cb0ee-87f5-4c86-9f88-c9d96eb04971)
![Image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/52354124/158bfe84-bf45-4c42-ac51-d2f5765542cf)

**Comment by alexrobincrabbe** [comment]
this is what it looks like to me 
![image](https://github.com/DesislavaNaydenova/2405-hackathon-team1-StarWars/assets/157045573/52995f31-d28e-46eb-8035-89bf70f39c4c)

**Comment by kera-cudmore** [comment]
same, I'm not seeing the question counter on the quiz page before I click start

**Comment by kslg** [comment]
ok for me now
